import React, { useState, useEffect } from 'react';

const QRModal = ({ qrCode, onClose, expiresAt }) => {
  const [timeLeft, setTimeLeft] = useState('');

  useEffect(() => {
    if (!expiresAt) return;
    const interval = setInterval(() => {
        const diff = new Date(expiresAt) - new Date();
        if (diff <= 0) {
            setTimeLeft('EXPIRED');
            clearInterval(interval);
        } else {
            const mins = Math.floor(diff / 60000);
            const secs = Math.floor((diff % 60000) / 1000);
            setTimeLeft(`${mins}m ${secs}s`);
        }
    }, 1000);
    return () => clearInterval(interval);
  }, [expiresAt]);

  if (!qrCode) return null;

  return (
    <div className="modal-overlay animate-in" onClick={onClose} style={{
        position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
        background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 4000
    }}>
      <div className="glass qr-modal-content" onClick={(e) => e.stopPropagation()} style={{
          padding: '32px', textAlign: 'center', maxWidth: '400px', borderRadius: '24px'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
             <h2 style={{ fontSize: '1.25rem', margin: 0, fontWeight: 800 }}>Security Pass</h2>
             <span className={`status-badge ${timeLeft === 'EXPIRED' ? 'badge-error' : 'badge-active'}`} style={{
                 padding: '4px 12px', borderRadius: '20px', fontSize: '0.7rem', fontWeight: 700,
                 background: timeLeft === 'EXPIRED' ? 'rgba(239, 68, 68, 0.1)' : 'rgba(16, 185, 129, 0.1)',
                 color: timeLeft === 'EXPIRED' ? 'var(--error)' : 'var(--success)',
                 border: `1px solid ${timeLeft === 'EXPIRED' ? 'var(--error)' : 'var(--success)'}`
             }}>
                 {timeLeft === 'EXPIRED' ? 'EXPIRED' : 'ACTIVE'}
             </span>
        </div>

        <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginBottom: '24px' }}>
          This pass is valid for one-time entry/exit until the timer below reaches zero.
        </p>
        
        <div style={{ background: 'white', padding: '24px', borderRadius: '16px', display: 'inline-block', marginBottom: '24px', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' }}>
          <img src={qrCode} alt="Security Pass" style={{ width: '200px', height: '200px' }} />
        </div>

        <div style={{ background: 'rgba(0,0,0,0.03)', padding: '16px', borderRadius: '12px', marginBottom: '24px' }}>
           <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase', marginBottom: '4px' }}>Time Remaining</div>
           <div style={{ fontSize: '1.5rem', fontWeight: 900, color: timeLeft === 'EXPIRED' ? 'var(--error)' : 'var(--primary)' }}>
              {timeLeft}
           </div>
        </div>

        <div style={{ display: 'flex', gap: '12px' }}>
            <button className="btn btn-primary" style={{ flex: 1 }} onClick={onClose}>
              Done
            </button>
        </div>

        <div style={{ marginTop: '24px', fontSize: '0.7rem', color: 'var(--text-muted)' }}>
          🔒 Securely generated by <strong>ParkSmart Enterprise</strong>
        </div>
      </div>
    </div>
  );
};

export default QRModal;
